version: "3.1"
services:
  teste-postgres-compose:
    image: postgres
    container_name: troca-app
    environment:
      POSTGRES_USER: troca
      POSTGRES_PASSWORD: troca
      POSTGRES_DB: troca
    ports:
      - "5434:5432"

